name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain
      - langchain-community
      {% if cookiecutter.vector_store == "faiss" %}
      - faiss-cpu
      {% else %}
      - chromadb
      {% endif %}
      - transformers
      - sentence-transformers
      - huggingface_hub
      - streamlit
      - ruff
      - pytest